export const ERROR_CODES = {
  INVALID_DAG: "INVALID_DAG",
  NODE_NOT_IMPLEMENTED: "NODE_NOT_IMPLEMENTED",
  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  KB_NOT_FOUND: "KB_NOT_FOUND",
  LLM_REQUEST_FAILED: "LLM_REQUEST_FAILED"
} as const;
